#TP 3 : Applications de base "Numpy"

### a -  A l'aide de la bibliothèque numpy, écrire un programme qui permet de créer une matrice du type  3x3 formée des entiers 1 , 2 , 3 , ... , 9.

In [2]:
import numpy as np

M = np.arange(1, 10).reshape(3, 3)
print(M)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


### b -  Créer un programme qui calcul la transposée de la matrice suivante à l'aide de la bibliothèque numpy : M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9,]])

In [3]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
T = M.T
print(T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


### c - Ecrire une fonction en python qui prends en argument une matrice numpy carrée du type nxn et  qui renvoie sa trace. On rappelle que la trace d'une matrice carrée A = (aij) i , j est le nombre  Tr(A) = a11 + a22 + ... + ann

In [4]:
def trace_matrice(A):
    if A.shape[0] != A.shape[1]:
        raise ValueError("La matrice doit être carrée !")

    trace = 0
    for i in range(A.shape[0]):
        trace += A[i, i]
    return trace

In [5]:
n = int(input("Donner la dimension n de la matrice carrée : "))

print(f"\nEntrez les {n*n} valeurs de la matrice (séparées par des espaces) :")
values = input("> ").split()


if len(values) != n*n:
    raise ValueError(f"Vous devez entrer exactement {n*n} valeurs !")


values = [float(v) for v in values]


A = np.array(values).reshape(n, n)

print("\nMatrice entrée :")
print(A)

# Trace
print("\nLa trace de la matrice est :", trace_matrice(A))


Entrez les 9 valeurs de la matrice (séparées par des espaces) :

Matrice entrée :
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

La trace de la matrice est : 15.0


### d - Ecrire un programme python numpy qui convertit une matrice numpy binaire (contenant uniquement des 0 et des 1) en une matrice numpy booléenne (c.a.d les '1' seront remplacés par True et les '0' par False)

In [6]:
def binaire_bool(A):
    return A.astype(bool)

In [7]:
A = np.array([[1,0,1],[0,1,0],[1,1,0]])

B = binaire_bool(A)
print(A)
print(B)

[[1 0 1]
 [0 1 0]
 [1 1 0]]
[[ True False  True]
 [False  True False]
 [ True  True False]]


### e - Ecrire un programme python numpy qui permet d'empiler 2 marices numpy horizontalement, c'est-à-dire 2 tableaux ayant la même 1ère dimension (même nombre de lignes)

In [8]:
def empiler(A , B):
    if A.shape[0] != B.shape[0]:
        raise ValueError("Les deux matrices doivent avoir le même nombre de lignes !")
    return np.hstack((A, B))

In [9]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10]])

C = empiler(A, B)

print(C)


[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


### f - Ecrire un programme python numpy permettant d'empilez 2 matrices numpy verticalement, c'est-à-dire 2 tableaux ayant la même dernière dimension (même nombre de colonnes)

In [10]:
def empiler_vertical(A , B):
    if A.shape[0] != B.shape[0]:
        raise ValueError("les deux matrice doivent avoire le meme nombre de lignes !et de colone        ")

    return np.hstack((A, B))

In [11]:
D = np.array([[1, 2, 3],
              [4, 5, 6]])

E = np.array([[7, 8],
              [9, 10]])

F = empiler_vertical(D, E)

print(F)

[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


### g - Ecrire un programme python numpy qui renvoie la multiplication de deux matrices numpy.

In [12]:
A = np.array([[1, 2, 3],[4, 5, 6]])
B = np.array([[7, 8, 9],[10, 11, 12]])

#multiplication de deux matrices
C = np.multiply(A, B)

#addition de deux matrices
D = np.add(A, B)

#soustraction 
E = np.subtract(A,B)

print("la multiplication de deux matrices est : \n",  C)
print("la addition de deux matrices est :", D)


la multiplication de deux matrices est : 
 [[ 7 16 27]
 [40 55 72]]
la addition de deux matrices est : [[ 8 10 12]
 [14 16 18]]


### h - Ecrire un programme python-numpy permettant de remplacer les éléments diagonaux d'une  matrice numpy par des 'zéros' 

In [13]:
import  numpy as np
def zero_diagonale(A):
    M = A.copy()
    np.fill_diagonal(M, 0)
    return M


In [14]:
A = np.array([[4, 1, 2],
              [3, 5, 7],
              [8, 9, 6]])

B = zero_diagonale(A)

print("Matrice originale :")
print(A)

print("\nMatrice avec diagonale à zéro :")
print(B)


Matrice originale :
[[4 1 2]
 [3 5 7]
 [8 9 6]]

Matrice avec diagonale à zéro :
[[0 1 2]
 [3 0 7]
 [8 9 0]]


### i - Ecrire un algorithme en Python numpy sous forme de fonction qui teste le type d'une matrice et renvoie True si la matrice est carrée du type nxn et False si non. 

In [15]:
def check_carre(matrice):
    if matrice.shape[0] != matrice.shape[1]:
        return False
    return True
N = np.random.randint(1,9,size=(3,2))
check_carre(N)

False

### j - Ecrire un programme en python numpy qui prend en paramètre une matrice numpy et renvoie  son déterminant lorsque la matrice est carrée et un message indiquant à l'utilisateur de choisir  une matrice carrée dans le cas contraire. 

In [ ]:
def det_m(matrice):
    if matrice.shape[0] != matrice.shape[1]:
         'Matrice non carre !'
    return np.linalg.det(matrice)
F = np.random.randint(1,9,size=(3,3))
print(F)
print("le determinant de F est : ",det_m(F))

## Constructions de matrices 

### 1 - Ecrire une fonction mata qui reçoit en argument un entier non nul n et  renvoie un tableau  numpy correspondant à la matrice ci-dessus. 

In [16]:
def mata(n):
    return np.eye(n)

print(mata(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 2 - Ecrire une fonction matb qui reçoit en argument un entier non nul n et renvoie un tableau numpy correspondant à la matrice ci-dessus.

In [17]:
def matb(n):
    M = np.eye(n, dtype=int)               # diagonale principale
    M += np.eye(n, k=1, dtype=int)         # diagonale supérieure
    M += np.eye(n, k=-1, dtype=int)        # diagonale inférieure
    return M

print(matb(5))

[[1 1 0 0 0]
 [1 1 1 0 0]
 [0 1 1 1 0]
 [0 0 1 1 1]
 [0 0 0 1 1]]


### 3 - Ecrire une fonction matc qui reçoit en argument un entier non nul n et renvoie un tableau numpy correspondant à la matrice ci-dessus.

In [19]:
def matc(n):
    # indices i et j
    i = np.arange(n).reshape(n, 1)   # colonne (n,1)
    j = np.arange(n).reshape(1, n)   # ligne  (1,n)
    M = j - i + 1                    
    M[M < 1] = 1                      # remplacer les valeurs <1 par 1
    return M.astype(int)

print(matc(6))

[[1 2 3 4 5 6]
 [1 1 2 3 4 5]
 [1 1 1 2 3 4]
 [1 1 1 1 2 3]
 [1 1 1 1 1 2]
 [1 1 1 1 1 1]]


### 4 - 

In [20]:
#MatArith1 :  arange + reshape
def MatArith1(n, u0, r):
    return (u0 + r * np.arange(n*n)).reshape(n, n)
print("\n la premiere methode : Matharith1 \n")
print(MatArith1(3, 1, 2))

#MatArith2 : arange et les sous-tableaux
def MatArith2(n, u0, r):
    M = u0 + r * np.arange(n*n)
    return np.array([M[i*n:(i+1)*n] for i in range(n)])
print("\n la deuxieme methode : Matharith2 \n")
print(MatArith2(3, 1, 2))

#MatArith3 : ni arrange ni rien
def MatArith3(n, u0, r):
    M = []
    val = u0
    for i in range(n):
        ligne = []
        for j in range(n):
            ligne.append(val)
            val += r
        M.append(ligne)
    return M
print("\n la troisieme methode : Matharith3 \n")
M = MatArith3(3, 1, 2)
for ligne in M:
    print(ligne)




 la premiere methode : Matharith1 

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]

 la deuxieme methode : Matharith2 

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]

 la troisieme methode : Matharith3 

[1, 3, 5]
[7, 9, 11]
[13, 15, 17]


### 5 - Ecrire une fonction SAS qui reçoit en argument un tableau carré M et renvoie un tuple de deux tableaux carrés de même dimension que celle de M, le premier étant symétrique et le second antisymétrique. On utilisera la fonction transpose de la bibliothèque numpy. 

In [23]:
def SAS(M):
    S = (M + M.T) / 2
    A = (M - M.T) / 2
    return S, A
# Exemple de matrice
M = np.arange(1,10).reshape(3,3)

S, A = SAS(M)

print("M =")
print(M)

print("\nPartie symétrique S =")
print(S)

print("\nPartie antisymétrique A =")
print(A)





M =
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Partie symétrique S =
[[1. 3. 5.]
 [3. 5. 7.]
 [5. 7. 9.]]

Partie antisymétrique A =
[[ 0. -1. -2.]
 [ 1.  0. -1.]
 [ 2.  1.  0.]]


In [24]:
### 6 - Ecrire une fonction qui reçoit en argument un tableau carré M et renvoie un tuple de deux tableaux carrés de même dimension que celle de M, le premier étant symétrique et le second antisymétrique. On utilisera la fonction transpose de la bibliothèque numpy. 
def IsDiag(M):
    return np.all(M == np.diag(np.diagonal(M)))

def IsTriang(M):
    if np.allclose(M, np.triu(M)):
        if IsDiag(M):
            return (True, 'D')
        return (True, 'U')
    elif np.allclose(M, np.tril(M)):
        if IsDiag(M):
            return (True, 'D')
        return (True, 'L')
    return False


M = np.array([[3, 0, 0],[0, 5, 0],[0, 0, 7]])

print(IsDiag(M))        
print(IsTriang(M))

True
(True, 'D')
